name: Build Qt Project

on: push

jobs:
  build:
    name: Build Qt Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        run: |
          sudo apt-get update

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          modules: 'qtmultimedia'

      - name: Add Qt to PATH
        run: echo "$HOME/Qt/6.7.0/gcc_64/bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          mkdir build2
          cd build2
          qmake ../GUI/semi.pro  # Adjusted .pro file path
          make
